version: "2.4"
services:
    wyze-bridge:
        container_name: wyze-bridgev2-4
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            - WYZE_EMAIL=gclaus@gmail.com
            - WYZE_PASSWORD=1002121wZ!
            - WB_IP=192.168.217.205
